# Generated by Django 4.2.7 on 2023-12-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urunler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urunAdi', models.CharField(max_length=100, verbose_name='Ürün Adı: ')),
                ('urunAciklamasi', models.TextField(max_length=500)),
            ],
        ),
    ]
