# Generated by Django 4.2.7 on 2023-12-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='fiyat',
            field=models.IntegerField(default=0),
        ),
    ]
