# Generated by Django 4.2.7 on 2023-12-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_urunler_fiyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='urunler',
            name='urunResim',
            field=models.FileField(blank=True, null=True, upload_to='urunResmi'),
        ),
    ]
